import type { Metadata } from "next";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import "./globals.scss";
import Navbar from "./components/Navbar/Navbar";
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'], 
  variable: '--font-inter',
  display: 'swap', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} bg-white antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
